In [1]:
!pip install h2o

Collecting h2o
  Downloading h2o-3.46.0.12.tar.gz (266.3 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 266.3/266.3 MB 4.7 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Requirement already satisfied: requests in /usr/local/lib/python3.13/dist-packages (from h2o) (2.32.4)
Requirement already satisfied: tabulate in /usr/local/lib/python3.13/dist-packages (from h2o) (0.9.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.13/dist-packages (from requests->h2o) (3.4.9)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.13/dist-packages (from requests->h2o) (3.19)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.13/dist-packages (from requests->h2o) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.13/dist-packages (from requests->h2o) (2026.7.22)
Building wheels for collected packages: h2o
  Building wheel for h2o (setup.py) ... done
  Created wheel for h2o: filename=h2o-3.46.0.12-py2.py3-none-any.whl size=266411167 sha256=5e6915181db00feb559d9f841516e0a8c5075545e682736957ef387f842551d2
  Stored in directory: /root/.cache/pip/wheels/2d/d1/1c/742fac210b3d4c1578163533b3f96a51659aac2702838347af
Successfully built h2o
Installing collected packages: h2o
Successfully installed h2o-3.46.0.12

In [2]:
import h2o
from h2o.automl import H2OAutoML

In [4]:
h2o.init()

Checking whether there is an H2O instance running at http://localhost:54321..... not found.
Attempting to start a local H2O server...
  Java Version: [0.025s][warning][os,container] Cgroup memory controller path at '/sys/fs/cgroup' seems to have moved to '/../../jupyter-children', detected limits won't be accurate; [0.025s][warning][os,container] Cgroup cpu controller path at '/sys/fs/cgroup' seems to have moved to '/../../jupyter-children', detected limits won't be accurate; openjdk version "21.0.11" 2026-04-21; OpenJDK Runtime Environment (build 21.0.11+10-1-22.04.2-Ubuntu); OpenJDK 64-Bit Server VM (build 21.0.11+10-1-22.04.2-Ubuntu, mixed mode, sharing)
  Starting server from /usr/local/lib/python3.13/dist-packages/h2o/backend/bin/h2o.jar
  Ice root: /tmp/tmpkbhts35z
  JVM stdout: /tmp/tmpkbhts35z/h2o_unknownUser_started_from_python.out
  JVM stderr: /tmp/tmpkbhts35z/h2o_unknownUser_started_from_python.err
  Server is running at http://127.0.0.1:54321
Connecting to H2O server at http://127.0.0.1:54321 ... successful.

--------------------------  -----------------------------------------------------------------------------------------
H2O_cluster_uptime:         03 secs
H2O_cluster_timezone:       Etc/UTC
H2O_data_parsing_timezone:  UTC
H2O_cluster_version:        3.46.0.12
H2O_cluster_version_age:    16 days
H2O_cluster_name:           H2O_from_python_unknownUser_ijlh1m
H2O_cluster_total_nodes:    1
H2O_cluster_free_memory:    3.149 Gb
H2O_cluster_total_cores:    2
H2O_cluster_allowed_cores:  2
H2O_cluster_status:         locked, healthy
H2O_connection_url:         http://127.0.0.1:54321
H2O_connection_proxy:       {"http": null, "https": null, "colab_language_server": "/usr/colab/bin/language_service"}
H2O_internal_security:      False
Python_version:             3.13.15 final
H2O_telemetry_server:       disabled
H2O_telemetry_client:       disabled
--------------------------  -----------------------------------------------------------------------------------------

+------------------------------------------------------------------+
| You are running the community edition of H2O-3 OSS.              |
|                                                                  |
| For commercial use, H2O-3 Secure is now recommended.             |
| This includes production support, CVE fixes, multi-node scaling, |
| model artifact extraction, and more.                             |
| See h2o.ai/h2o-3/oss-vs-secure for additional details.           |
| Contact enterprise@h2o.ai to upgrade.                            |
+------------------------------------------------------------------+

In [5]:
data = h2o.import_file('insurance.csv')

Parse progress: |████████████████████████████████████████████████████████████████| (done) 100%

In [6]:
data

  C1  GoodStudent    Age         SocioEcon    RiskAversion    VehicleYear    ThisCarDam    RuggedAuto    Accident    MakeModel    DrivQuality    Mileage     Antilock    DrivingSkill    SeniorTrain    ThisCarCost    Theft    CarValue    HomeBase    AntiTheft    PropCost     OtherCarCost    OtherCar    MedCost    Cushioning    Airbag    ILiCost    DrivHist
----  -------------  ----------  -----------  --------------  -------------  ------------  ------------  ----------  -----------  -------------  ----------  ----------  --------------  -------------  -------------  -------  ----------  ----------  -----------  -----------  --------------  ----------  ---------  ------------  --------  ---------  ----------
   1  False          Adult       Prole        Adventurous     Older          Moderate      EggShell      Mild        Economy      Poor           TwentyThou  False       SubStandard     False          TenThou        False    FiveThou    City        False        TenThou      Thousand        True        Thousand   Poor          False     Thousand   Many
   2  False          Senior      Prole        Cautious        Current        None          Football      None        Economy      Normal         TwentyThou  False       Normal          True           Thousand       False    TenThou     City        True         Thousand     Thousand        True        Thousand   Good          True      Thousand   Zero
   3  False          Senior      UpperMiddle  Psychopath      Current        None          Football      None        FamilySedan  Excellent      Domino      True        Normal          False          Thousand       False    TwentyThou  City        False        Thousand     Thousand        False       Thousand   Good          True      Thousand   One
   4  False          Adolescent  Middle       Normal          Older          None          EggShell      None        Economy      Normal         FiftyThou   False       Normal          False          Thousand       False    FiveThou    Suburb      False        Thousand     Thousand        True        Thousand   Fair          False     Thousand   Zero
   5  False          Adolescent  Prole        Normal          Older          Moderate      Football      Moderate    Economy      Poor           FiftyThou   False       SubStandard     False          TenThou        False    FiveThou    City        False        TenThou      Thousand        False       Thousand   Fair          False     Thousand   Many
   6  False          Adult       UpperMiddle  Normal          Current        Moderate      EggShell      Moderate    SportsCar    Poor           FiftyThou   True        SubStandard     False          HundredThou    False    TwentyThou  Suburb      True         HundredThou  HundredThou     True        TenThou    Poor          True      Thousand   Many
   7  False          Senior      UpperMiddle  Normal          Current        Mild          Football      Mild        Economy      Poor           FiveThou    False       SubStandard     False          TenThou        False    TenThou     Secure      True         TenThou      Thousand        False       Thousand   Excellent     True      Thousand   Many
   8  False          Adult       Prole        Normal          Older          Severe        EggShell      Severe      Economy      Poor           TwentyThou  False       SubStandard     False          TenThou        False    TenThou     City        False        Million      HundredThou     True        Thousand   Fair          False     Thousand   Many
   9  False          Adult       Prole        Normal          Older          Severe        EggShell      Severe      Economy      Poor           TwentyThou  False       SubStandard     False          TenThou        False    FiveThou    City        False        HundredThou  TenThou         False       TenThou    Poor          False     Thousand   Many
  10  True           Adolescent  Prole        Cautious        Older          Severe        Football      Severe      FamilySedan  Poor           TwentyThou  False       SubStandard     False          TenThou        False    FiveThou    City        True         HundredThou  HundredThou     True        Thousand   Good          False     Thousand   Many
[20000 rows x 28 columns]

In [7]:
data = data.drop("C1")

In [8]:
treino, teste = data.split_frame(ratios=[0.7], seed=0)

In [9]:
model_automl = H2OAutoML(max_runtime_secs=180, sort_metric='AUC')
model_automl.train(y="Accident", training_frame=treino)

AutoML progress: |██████████████████
06:21:54.458: GLM_1_AutoML_1_20260828_62103 [GLM def_1] failed: java.lang.ArrayIndexOutOfBoundsException: Index 83 out of bounds for length 83

█████████████████████████████████████████████| (done) 100%

Model Details
=============
H2ORandomForestEstimator : Distributed Random Forest
Model Key: DRF_1_AutoML_1_20260828_62103


Model Summary:
    number_of_trees    number_of_internal_trees    model_size_in_bytes    min_depth    max_depth    mean_depth    min_leaves    max_leaves    mean_leaves
--  -----------------  --------------------------  ---------------------  -----------  -----------  ------------  ------------  ------------  -------------
    1                  4                           21806                  19           20           19.75         267           550           430.25

ModelMetricsMultinomial: drf
** Reported on train data. **

MSE: 0.0820913584490272
RMSE: 0.28651589563063895
LogLoss: 2.4188882637275975
Mean Per-Class Error: 0.21173222001027758
AUC table was not computed: it is either disabled (model parameter 'auc_type' was set to AUTO or NONE) or the domain size exceeds the limit (maximum is 50 domains).
AUCPR table was not computed: it is either disabled (model parameter 'auc_type' was set to AUTO or NONE) or the domain size exceeds the limit (maximum is 50 domains).

Confusion Matrix: Row labels: Actual class; Column labels: Predicted class
Mild    Moderate    None    Severe    Error       Rate
------  ----------  ------  --------  ----------  -----------
312     34          97      1         0.297297    132 / 444
27      255         53      88        0.397163    168 / 423
23      1           3668    3         0.00730717  27 / 3,695
2       39          49      530       0.145161    90 / 620
364     329         3867    622       0.0804709   417 / 5,182

Top-4 Hit Ratios:
k    hit_ratio
---  -----------
1    0.919529
2    0.948283
3    0.948669
4    1

ModelMetricsMultinomial: drf
** Reported on cross-validation data. **

MSE: 0.06754468372608348
RMSE: 0.25989360077940254
LogLoss: 1.7720166348228332
Mean Per-Class Error: 0.1914569678790859
AUC table was not computed: it is either disabled (model parameter 'auc_type' was set to AUTO or NONE) or the domain size exceeds the limit (maximum is 50 domains).
AUCPR table was not computed: it is either disabled (model parameter 'auc_type' was set to AUTO or NONE) or the domain size exceeds the limit (maximum is 50 domains).

Confusion Matrix: Row labels: Actual class; Column labels: Predicted class
Mild    Moderate    None    Severe    Error       Rate
------  ----------  ------  --------  ----------  --------------
911     93          206     12        0.254501    311 / 1,222
108     736         57      227       0.347518    392 / 1,128
50      11          9990    1         0.00616793  62 / 10,052
57      139         66      1400      0.157641    262 / 1,662
1126    979         10319   1640      0.0730233   1,027 / 14,064

Top-4 Hit Ratios:
k    hit_ratio
---  -----------
1    0.926977
2    0.962528
3    0.964519
4    1

Cross-Validation Metrics Summary:
                         mean       sd         cv_1_valid    cv_2_valid    cv_3_valid    cv_4_valid    cv_5_valid
-----------------------  ---------  ---------  ------------  ------------  ------------  ------------  ------------
accuracy                 0.926977   0.0123709  0.919303      0.910416      0.928191      0.940988      0.935989
aic                      nan        0          nan           nan           nan           nan           nan
auc                      nan        0          nan           nan           nan           nan           nan
err                      0.0730227  0.0123709  0.0806968     0.0895841     0.0718095     0.0590117     0.0640114
err_count                205.4      34.8109    227           252           202           166           180
loglikelihood            nan        0          nan           nan           nan           nan           nan
logloss                  1.77198    0.728244   2.319         2.77117       1.33323       1.12332       1.31319
max_per_class_error      0.347597   0.0449563  0.375         0.40553       0.347826      0.317391      0.292237
mean_per_class_accuracy  0.808605   0.0265072  0.790421      0.774967      0.81243       0.842141      0.823064
mean_per_class_error     0.191395   0.0265072  0.209578      0.225033      0.18757       0.157859      0.176936
mse                      0.0675439  0.0163136  0.078295      0.09082       0.0594579     0.0529443     0.0562021
pr_auc                   nan        0          nan           nan           nan           nan           nan
r2                       0.872051   0.0300253  0.8515        0.829861      0.887703      0.900603      0.890586
rmse                     0.258436   0.03071    0.279812      0.301364      0.24384       0.230096      0.23707

Scoring History:
    timestamp            duration    number_of_trees    training_rmse    training_logloss    training_classification_error    training_auc    training_pr_auc
--  -------------------  ----------  -----------------  ---------------  ------------------  -------------------------------  --------------  -----------------
    2026-08-28 06:23:50  3.588 sec   0                  nan              nan                 nan                              nan             nan
    2026-08-28 06:23:50  4.226 sec   1                  0.286516         2.41889             0.0804709                        nan             nan

Variable Importances:
variable      relative_importance    scaled_importance       percentage
------------  ---------------------  ----------------------  ---------------------
ThisCarDam    2595.7939453125        1.0                     0.6345258065984835
ILiCost       465.9777526855469      0.179512612519577       0.11390538525358562
ThisCarCost   199.31219482421875     0.07678274894821212     0.04872063570921315
OtherCarCost  101.62187194824219     0.03914866668510093     0.02484083930561885
RiskAversion  81.89240264892578      0.031548113746396385    0.020018092321592868
Mileage       58.52483367919922      0.022546024419574484    0.014306034330419604
RuggedAuto    56.98575973510742      0.02195311374310455     0.013929817205191666
HomeBase      53.04079818725586      0.02043336231792868     0.012965495706302753
PropCost      52.65191650390625      0.020283550086471768    0.012870435979299237
CarValue      44.82676696777344      0.017269000510892585    0.01095762647832374
---           ---                    ---                     ---
DrivHist      27.693883895874023     0.010668752789829023    0.006769598969366082
OtherCar      27.59389877319336      0.010630234662124313    0.006745158223315587
DrivQuality   26.7424373626709       0.010302218868705873    0.00653702373741971
Airbag        15.931078910827637     0.006137266380328867    0.0038942539002879296
Antilock      14.293848991394043     0.005506542234296355    0.0034940431527855096
AntiTheft     13.200916290283203     0.005085502381312467    0.0032268825004608016
VehicleYear   11.138398170471191     0.0042909408085279556   0.00272271267759755
GoodStudent   7.197048664093018      0.0027725808811171204   0.0017592741199503748
SeniorTrain   5.060006141662598      0.0019493096325307279   0.0012368872668917534
Theft         0.98128342628479       0.00037802824375054783  0.0002398686762828245
[26 rows x 4 columns]


[tips]
Use `model.explain()` to inspect the model.
--
Use `h2o.display.toggle_user_tips()` to switch on/off this section.

In [10]:
 ranking = model_automl.leaderboard
 ranking = ranking.as_data_frame()
 ranking

/usr/local/lib/python3.13/dist-packages/h2o/frame.py:1983: H2ODependencyWarning: Converting H2O frame to pandas dataframe using single-thread.  For faster conversion using multi-thread, install polars and pyarrow and use it as pandas_df = h2o_df.as_data_frame(use_multi_thread=True)

  warnings.warn("Converting H2O frame to pandas dataframe using single-thread.  For faster conversion using"

,model_id,auc,mean_per_class_error,logloss,rmse,mse
0,DRF_1_AutoML_1_20260828_62103,NaN,0.191457,1.772017,0.259894,0.067545
1,XGBoost_1_AutoML_1_20260828_62103,NaN,0.145131,0.137491,0.199152,0.039661
2,GBM_4_AutoML_1_20260828_62103,NaN,0.146602,0.819646,0.556955,0.310199
3,StackedEnsemble_BestOfFamily_1_AutoML_1_202608...,NaN,0.140991,0.133670,0.197140,0.038864
4,XGBoost_2_AutoML_1_20260828_62103,NaN,0.144982,0.610114,0.455938,0.207879
5,GBM_2_AutoML_1_20260828_62103,NaN,0.151160,0.886303,0.585615,0.342945
6,StackedEnsemble_BestOfFamily_2_AutoML_1_202608...,NaN,0.169671,0.228468,0.244667,0.059862
7,GBM_1_AutoML_1_20260828_62103,NaN,0.141503,0.136080,0.197421,0.038975
8,GBM_3_AutoML_1_20260828_62103,NaN,0.145785,0.652197,0.477216,0.227735
9,StackedEnsemble_AllModels_1_AutoML_1_20260828_...,NaN,0.168019,0.225610,0.242999,0.059049

In [11]:
prever = model_automl.leader.predict(teste)
prever

drf prediction progress: |███████████████████████████████████████████████████████| (done) 100%

predict      Mild    Moderate    None    Severe
---------  ------  ----------  ------  --------
None            0         0         1       0
Moderate        0         1         0       0
Severe          0         0         0       1
None            0         0         1       0
Mild            0         0.5       0       0.5
None            0         0         1       0
Mild            1         0         0       0
None            0         0         1       0
None            0         0         1       0
Severe          0         0         0       1
[5936 rows x 5 columns]