In [1]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder
from imblearn.over_sampling import SMOTENC

In [2]:
credito = pd.read_csv('credit_simple.csv', sep=';')
credito.head()

,SALDO_ATUAL,RESIDENCIADESDE,IDADE,OUTROSPLANOSPGTO,DATA,ESTADOCIVIL,PROPOSITO,CLASSE
0,1169.0,4,67,nenhum,01/01/2019,masculino solteiro,radio/tv,bom
1,5951.0,2,22,nenhum,01/01/2020,fem div/cas,radio/tv,ruim
2,2096.0,3,49,nenhum,02/01/2020,masculino solteiro,educação,bom
3,7882.0,4,45,nenhum,02/01/2019,masculino solteiro,mobilia/equipamento,bom
4,4870.0,4,53,nenhum,03/01/2018,masculino solteiro,carro novo,ruim

In [3]:
count = credito.groupby(['CLASSE']).size()
count

CLASSE
bom     700
ruim    300
dtype: int64

In [4]:
y = credito['CLASSE'].values
X = credito.iloc[:,:-1].values

In [6]:
labelencoder = LabelEncoder()
for i in range(X.shape[1]):
  if X[:,i].dtype == 'object':
    X[:,i] = labelencoder.fit_transform(X[:,i])

In [7]:
sm = SMOTENC(random_state=0, categorical_features=[3,5,6])
X_res, y_res = sm.fit_resample(X,y)

In [8]:
X_res

array([[140.0, 3.0, 49.0, ..., 0.0, 3, 9],
       [765.0, 1.0, 4.0, ..., 1.0, 0, 9],
       [388.0, 2.0, 31.0, ..., 13.0, 3, 3],
       ...,
       [80.39981214000933, 1.7996242800186615, 4.200375719981339, ...,
        34.99248560037323, 0, 1],
       [897.9858495639895, 3.0, 26.042451308031378, ...,
        140.35691739335076, 0, 2],
       [462.1024631463796, 1.9658456178734771, 5.6894362547510156, ...,
        297.2700607509019, 0, 4]], dtype=object)

In [9]:
df = pd.DataFrame({'CLASSE': y_res})
df.value_counts()

CLASSE
bom       700
ruim      700
Name: count, dtype: int64